version: '3.8'
services:
  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    ports:
      - "8081:3000"
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/version || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app-network

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    ports:
      - "8082:3000"
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/version || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
    depends_on:
      app_blue:
        condition: service_healthy
      app_green:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80/version || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge