services:
  nginx:
    image: nginx:latest
    ports:
      - "${PORT:-8080}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_blue
      - app_green
    restart: always

  app_blue:
    image: ${BLUE_IMAGE}
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}
    ports:
      - "8081:80"

  app_green:
    image: ${GREEN_IMAGE}
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}
    ports:
      - "8082:80"
